/** Declaration file generated by dts-gen */

export = gulp_livereload;

declare function gulp_livereload(opts?: any): any;

declare namespace gulp_livereload {
    const options: {
        quiet: boolean;
        reloadPage: string;
    };

    const server: any;

    function changed(filePath?: any): any;

    function listen(opts?: any, cb?: any, ...args: any[]): any;

    function middleware(opts: any): any;

    function reload(filePath?: any): any;

}

