/** Declaration file generated by dts-gen */
export interface livereloadServer {
    refresh: (path: string) => void;
}
export function createServer(config?: any, callback?: any): livereloadServer;

